export const AUTH_ERROR_MESSAGE = {
  'auth.invalid_credentials': {
    ko: '아이디 또는 비밀번호가 올바르지 않습니다.',
    ja: 'IDまたはパスワードが正しくありません。',
    zhCN: 'ID或密码不正确。',
    zhTW: 'ID或密碼不正確。',
    en: 'ID or password is incorrect.',
    vi: 'ID hoặc mật khẩu không chính xác.',
    ru: 'Неверный ID или пароль.',
    th: 'ID หรือรหัสผ่านไม่ถูกต้อง',
  },
  'auth.inactive_account': {
    ko: '퇴사한 직원의 계정입니다.',
    ja: '退職した従業員のアカウントです。',
    zhCN: '该账号已离职。',
    zhTW: '該帳號已離職。',
    en: 'This account is resigned.',
    vi: 'Tài khoản này đã nghỉ việc.',
    ru: 'Этот аккаунт уволен.',
    th: 'บัญชีนี้ถูกยกเลิก',
  },
  'auth.invalid_token': {
    ko: '유효하지 않은 토큰입니다.',
    ja: '無効なトークンです。',
    zhCN: '无效的令牌。',
    zhTW: '無效的令牌。',
    en: 'Invalid token.',
    vi: 'Token không hợp lệ.',
    ru: 'Недействительный токен.',
    th: 'โทเค็นไม่ถูกต้อง',
  },
  'auth.expired_token': {
    ko: '만료된 토큰입니다. 다시 로그인해주세요.',
    ja: 'トークンの有効期限が切れました。再度ログインしてください。',
    zhCN: '令牌已过期，请重新登录。',
    zhTW: '令牌已過期，請重新登錄。',
    en: 'Token has expired. Please log in again.',
    vi: 'Token đã hết hạn. Vui lòng đăng nhập lại.',
    ru: 'Срок действия токена истёк. Пожалуйста, войдите снова.',
    th: 'โทเค็นหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง',
  },
  'auth.no_permission': {
    ko: '접근 권한이 없습니다.',
    ja: 'アクセス権限がありません。',
    zhCN: '没有访问权限。',
    zhTW: '沒有訪問權限。',
    en: 'You do not have permission to access.',
    vi: 'Bạn không có quyền truy cập.',
    ru: 'У вас нет прав доступа.',
    th: 'คุณไม่มีสิทธิ์เข้าถึง',
  },
};
