export const COMMON_ERROR_MESSAGE = {
  'common.errorMessage': {
    ko: '서버 내부 오류가 발생했습니다.',
    ja: 'サーバー内部エラーが発生しました。',
    zhCN: '服务器内部错误',
    zhTW: '伺服器內部錯誤',
    en: 'Internal server error',
    vi: 'Lỗi máy chủ nội bộ',
    ru: 'Внутренняя ошибка сервера',
    th: 'ข้อผิดพลาดภายในเซิร์ฟเวอร์',
  },
  'common.not_found': {
    ko: '존재하지 않는 데이터입니다.',
    ja: '存在しないデータです。',
    zhCN: '不存在数据。',
    zhTW: '不存在數據。',
    en: 'Data not found.',
    vi: 'Dữ liệu không tồn tại.',
    ru: 'Данные не найдены.',
    th: 'ข้อมูลไม่พบ.',
  },
  'common.invalid_request': {
    ko: '잘못된 요청입니다.',
    ja: '無効なリクエストです。',
    zhCN: '无效请求',
    zhTW: '無效請求',
    en: 'Invalid request',
    vi: 'Yêu cầu không hợp lệ',
    ru: 'Неверный запрос',
    th: 'คำสั่งไม่ถูกต้อง',
  },
  'common.min_length_1': {
    ko: '최소 1자 이상 입력해주세요.',
    ja: '1文字以上入力してください。',
    zhCN: '请输入至少1个字。',
    zhTW: '請輸入至少1個字。',
    en: 'Please input at least 1 character.',
    vi: 'Vui lòng nhập ít nhất 1 ký tự.',
    ru: 'Пожалуйста, введите не менее 1 символа.',
    th: 'โปรดป้อนอย่างน้อย 1 ตัวอักษร.',
  },
  'common.priority.required': {
    ko: '변경 노출 우선순위는 필수 입력 값입니다.',
    ja: '変更表示優先順位は必須入力です。',
    zhCN: '变更显示优先顺序是必填输入值。',
    zhTW: '變更顯示優先順序是必填輸入值。',
    en: 'Priority is required.',
    vi: 'Độ ưu tiên là bắt buộc.',
    ru: 'Приоритет является обязательным.',
    th: 'ความสำคัญเป็นความจำเป็น.',
  },
  'common.translation_not_filled': {
    ko: '값을 입력해주세요.',
    ja: '値を入力してください。',
    zhCN: '值不存在。',
    zhTW: '值不存在。',
    en: 'Value is not filled.',
    vi: 'Giá trị không được điền.',
    ru: 'Значение не заполнено.',
    th: 'ค่าไม่ได้กรอก.',
  },
  'common.translation_not_updated': {
    ko: '기준값이 수정된 항목입니다.',
    ja: '基準値が修正された項目です。',
    zhCN: '基准值已修改的项目。',
    zhTW: '基準值已修改的項目。',
    en: 'Base value has been modified.',
    vi: 'Giá trị cơ sở đã được sửa đổi.',
    ru: 'Базовое значение было изменено.',
    th: 'ค่าฐานถูกแก้ไข.',
  },
  'common.translation_not_used': {
    ko: '기준값에서 사용되지 않은 항목입니다.',
    ja: '基準値が使用されていない項目です。',
    zhCN: '基准值未使用的项目。',
    zhTW: '基准值未使用的項目。',
    en: 'Base value is not used.',
    vi: 'Giá trị cơ sở không được sử dụng.',
    ru: 'Базовое значение не используется.',
    th: 'ค่าฐานไม่ได้ใช้งาน.',
  },
  'common.failed_to_delete': {
    ko: '삭제에 실패했습니다.',
    ja: '削除に失敗しました。',
    zhCN: '删除失败。',
    zhTW: '刪除失敗。',
    en: 'Failed to delete.',
    vi: 'Xóa thất bại.',
    ru: 'Удаление не удалось.',
    th: 'การลบไม่สำเร็จ.',
  },
  'common.not_deleted_condition': {
    ko: '삭제 요건 충족 불가능',
    ja: '削除条件を満たしていません。',
    zhCN: '删除条件不满足。',
    zhTW: '刪除條件不滿足。',
    en: 'Not deleted not condition.',
    vi: 'Không thể xóa không điều kiện.',
    ru: 'Невозможно удалить без условия.',
    th: 'ไม่สามารถลบได้โดยไม่มีเงื่อนไข.',
  },
  'common.not_allowed': {
    ko: '허용되지 않는 요청입니다.',
    ja: '許可されていないリクエストです。',
    zhCN: '不允许的请求。',
    zhTW: '不允許的請求。',
    en: 'Operation not allowed.',
    vi: 'Yêu cầu không được phép.',
    ru: 'Операция не разрешена.',
    th: 'คำขอไม่ได้รับอนุญาต.',
  },
  'common.over_payment': {
    ko: '미납 금액을 초과한 결제입니다.',
    ja: '未納金額を超過した決済です。',
    zhCN: '超过未付金额的支付。',
    zhTW: '超過未付金額的支付。',
    en: 'Payment exceeds unpaid amount.',
    vi: 'Thanh toán vượt quá số tiền chưa thanh toán.',
    ru: 'Платеж превышает неоплаченную сумму.',
    th: 'การชำระเงินเกินยอดค้างชำระ.',
  },
}
