export const OPERATION_ERROR_MESSAGE = {
  'operation.not_found': {
    ko: '시술을 찾을 수 없습니다.',
    ja: '時間を見つけることができません。',
    zhCN: '时间找不到。',
    zhTW: '時間找不到。',
    en: 'Operation not found.',
    vi: 'Không tìm thấy thời gian.',
    ru: 'Время не найдено.',
    th: 'ไม่พบเวลา.',
  },

  'operation.category.not_deleted': {
    ko: '연결된 시술을 제거한 후 시술 분류를 삭제해주세요.',
    ja: '関連する時間を削除した後、時間分類を削除してください。',
    zhCN: '删除相关时间后再删除时间分类。',
    zhTW: '刪除相關時間後再刪除時間分類。',
    en: 'Please delete the related operation after deleting the operation category.',
    vi: 'Xóa thời gian liên quan sau đó xóa danh mục thời gian.',
    ru: 'Удалите связанное время, затем удалите категорию времени.',
    th: 'ลบการเกี่ยวข้องกับเวลาก่อนลบหมวดหมู่เวลา.',
  },
  'operation.name.required': {
    ko: '시술 명은 필수 입력 값입니다.',
    ja: '時間名は必須入力です。',
    zhCN: '时间名是必填输入值。',
    zhTW: '時間名是必填輸入值。',
    en: 'Operation name is required.',
    vi: 'Tên thời gian là bắt buộc.',
    ru: 'Название времени является обязательным.',
    th: 'ชื่อเวลาเป็นความจำเป็น.',
  },

  'operation.name.string': {
    ko: '시술 명은 문자열 형식이어야 합니다.',
    ja: '時間名は文字列形式でなければなりません。',
    zhCN: '时间名必须是字符串格式。',
    zhTW: '時間名必須是字符串格式。',
    en: 'Operation name must be a string format.',
    vi: 'Tên thời gian phải là định dạng chuỗi.',
    ru: 'Название времени должно быть в строковом формате.',
    th: 'ชื่อเวลาต้องเป็นรูปแบบของสตริง.',
  },

  'operation.name.duplicate': {
    ko: '시술 명이 중복되었습니다.',
    ja: '時間名が重複しました。',
    zhCN: '时间名重复。',
    zhTW: '時間名重複。',
    en: 'Operation name duplicate.',
    vi: 'Tên thời gian trùng lặp.',
    ru: 'Название времени дублируется.',
    th: 'ชื่อเวลาซ้ำกัน.',
  },

  'operation.category.name.duplicate': {
    ko: '시술 분류 명이 중복되었습니다.',
    ja: '時間分類名が重複しました。',
    zhCN: '时间分类名重复。',
    zhTW: '時間分類名重複。',
    en: 'Operation category name duplicate.',
    vi: 'Tên danh mục thời gian trùng lặp.',
    ru: 'Название категории времени дублируется.',
    th: 'ชื่อหมวดหมู่เวลาซ้ำกัน.',
  },

  'operation.create.failed': {
    ko: '시술 생성에 실패했습니다.',
    ja: '時間作成に失敗しました。',
    zhCN: '时间创建失败。',
    zhTW: '時間創建失敗。',
    en: 'Operation creation failed.',
    vi: 'Tạo thời gian thất bại.',
    ru: 'Создание времени не удалось.',
    th: 'การสร้างเวลาไม่สำเร็จ.',
  },

  'operation.update.failed': {
    ko: '시술 수정에 실패했습니다.',
    ja: '時間更新に失敗しました。',
    zhCN: '时间更新失败。',
    zhTW: '時間更新失敗。',
    en: 'Operation update failed.',
    vi: 'Cập nhật thời gian thất bại.',
    ru: 'Обновление времени не удалось.',
    th: 'การปรับปรุงเวลาไม่สำเร็จ.',
  },

  'operation.translation.name.notChanged': {
    ko: '시술 번역 명이 변경되지 않았습니다.',
    ja: '時間翻訳名が変更されていません。',
    zhCN: '时间翻译名没有改变。',
    zhTW: '時間翻譯名沒有改變。',
    en: 'Operation translation name not changed.',
    vi: 'Tên dịch thời gian không thay đổi.',
    ru: 'Название перевода времени не изменилось.',
    th: 'ชื่อการแปลเวลาไม่ได้เปลี่ยนแปลง.',
  },

  'operation.remaining.not_found': {
    ko: '잔여시술을 찾을 수 없습니다.',
    ja: '残余施術が見つかりません。',
    zhCN: '找不到剩余手术。',
    zhTW: '找不到剩餘手術。',
    en: 'Remaining operation not found.',
    vi: 'Không tìm thấy thủ thuật còn lại.',
    ru: 'Оставшаяся операция не найдена.',
    th: 'ไม่พบการผ่าตัดที่เหลืออยู่.',
  },

  'operation.remaining.insufficient': {
    ko: '잔여시술 횟수가 부족합니다.',
    ja: '残余施術の回数が不足しています。',
    zhCN: '剩余手术次数不足。',
    zhTW: '剩餘手術次數不足。',
    en: 'Insufficient remaining operation count.',
    vi: 'Số lần thủ thuật còn lại không đủ.',
    ru: 'Недостаточно оставшихся операций.',
    th: 'จำนวนการผ่าตัดที่เหลืออยู่ไม่เพียงพอ.',
  },

  // 잔여시술 수동등록 (force_create)
  'operation.remaining.manual.operationId.required': {
    ko: '시술은 필수 입력 값입니다.',
    ja: '施術は必須入力です。',
    zhCN: '手术为必填输入值。',
    zhTW: '手術為必填輸入值。',
    en: 'Operation is required.',
    vi: 'Thủ thuật là bắt buộc.',
    ru: 'Операция обязательна.',
    th: 'การผ่าตัดเป็นความจำเป็น.',
  },

  'operation.remaining.manual.quantity.invalid': {
    ko: '등록 횟수는 1 이상이어야 합니다.',
    ja: '登録回数は1以上でなければなりません。',
    zhCN: '登记次数必须为1以上。',
    zhTW: '登記次數必須為1以上。',
    en: 'Quantity must be at least 1.',
    vi: 'Số lượng phải lớn hơn hoặc bằng 1.',
    ru: 'Количество должно быть не менее 1.',
    th: 'จำนวนต้องมีอย่างน้อย 1.',
  },

  'operation.remaining.manual.reason.required': {
    ko: '등록 사유는 필수 입력 값입니다.',
    ja: '登録事由は必須入力です。',
    zhCN: '登记事由为必填输入值。',
    zhTW: '登記事由為必填輸入值。',
    en: 'Registration reason is required.',
    vi: 'Lý do đăng ký là bắt buộc.',
    ru: 'Причина регистрации обязательна.',
    th: 'เหตุผลการลงทะเบียนเป็นความจำเป็น.',
  },

  'operation.remaining.manual.restCount.invalid': {
    ko: '남은 수량은 0 이상이어야 합니다.',
    ja: '残り数量は0以上でなければなりません。',
    zhCN: '剩余数量必须为0以上。',
    zhTW: '剩餘數量必須為0以上。',
    en: 'Remaining quantity must be at least 0.',
    vi: 'Số lượng còn lại phải lớn hơn hoặc bằng 0.',
    ru: 'Оставшееся количество должно быть не менее 0.',
    th: 'จำนวนที่เหลือต้องมีอย่างน้อย 0.',
  },

  'operation.remaining.manual.not_found': {
    ko: '수동등록한 잔여시술만 수정할 수 있습니다.',
    ja: '手動登録した残余施術のみ修正できます。',
    zhCN: '只能修改手动登记的剩余手术。',
    zhTW: '只能修改手動登記的剩餘手術。',
    en: 'Only manually registered remaining operations can be modified.',
    vi: 'Chỉ có thể chỉnh sửa thủ thuật còn lại được đăng ký thủ công.',
    ru: 'Изменять можно только вручную зарегистрированные оставшиеся операции.',
    th: 'สามารถแก้ไขได้เฉพาะการผ่าตัดที่เหลือที่ลงทะเบียนด้วยตนเองเท่านั้น.',
  },

  'operation-priority.not_deleted_only_category': {
    ko: '단일 카테고리는 삭제 불가능 합니다.',
    ja: '単一カテゴリは削除できません。',
    zhCN: '单一类别无法删除',
    zhTW: '單一類別無法刪除',
    en: 'Single category cannot be deleted',
    vi: 'Danh mục đơn không thể xóa',
    ru: 'Категория одного не может быть удалена',
    th: 'หมวดหมู่เดียวไม่สามารถลบได้',
  },
}