export const POPUP_ERROR_MESSAGE = {
  'basic-popup.not_found': {
    ko: '팝업을 찾을 수 없습니다.',
    ja: 'ポップアップが見つかりません。',
    zhCN: '找不到弹窗。',
    zhTW: '找不到彈窗。',
    en: 'Popup not found.',
    vi: 'Không tìm thấy popup.',
    ru: 'Всплывающее окно не найдено.',
    th: 'ไม่พบป๊อปอัป.',
  },
  'basic-popup.startAt.required': {
    ko: '시작일을 입력해주세요.',
    ja: '開始日を入力してください。',
    zhCN: '请输入开始日期。',
    zhTW: '請輸入開始日期。',
    en: 'Start date is required.',
    vi: 'Vui lòng nhập ngày bắt đầu.',
    ru: 'Введите дату начала.',
    th: 'กรุณากรอกวันที่เริ่มต้น.',
  },
  'basic-popup.startTime.required': {
    ko: '시작시간을 입력해주세요.',
    ja: '開始時間を入力してください。',
    zhCN: '请输入开始时间。',
    zhTW: '請輸入開始時間。',
    en: 'Start time is required.',
    vi: 'Vui lòng nhập giờ bắt đầu.',
    ru: 'Введите время начала.',
    th: 'กรุณากรอกเวลาเริ่มต้น.',
  },
  'basic-popup.endAt.required': {
    ko: '종료일을 입력해주세요.',
    ja: '終了日を入力してください。',
    zhCN: '请输入结束日期。',
    zhTW: '請輸入結束日期。',
    en: 'End date is required.',
    vi: 'Vui lòng nhập ngày kết thúc.',
    ru: 'Введите дату окончания.',
    th: 'กรุณากรอกวันที่สิ้นสุด.',
  },
  'basic-popup.endTime.required': {
    ko: '종료시간을 입력해주세요.',
    ja: '終了時間を入力してください。',
    zhCN: '请输入结束时间。',
    zhTW: '請輸入結束時間。',
    en: 'End time is required.',
    vi: 'Vui lòng nhập giờ kết thúc.',
    ru: 'Введите время окончания.',
    th: 'กรุณากรอกเวลาสิ้นสุด.',
  },
};
