export const PRODUCT_ERROR_MESSAGE = {
  'product.not_found': {
    ko: '상품을 찾을 수 없습니다.',
    ja: '商品を見つかりません。',
    zhCN: '商品找不到。',
    zhTW: '商品找不到。',
    en: 'Product not found.',
  },
  'product.category.not_found': {
    ko: '카테고리를 찾을 수 없습니다.',
    ja: 'カテゴリが見つかりません。',
    zhCN: '分类找不到。',
    zhTW: '分類找不到。',
    en: 'Category not found.',
  },
  'product.category.product.not_found': {
    ko: '카테고리 상품을 찾을 수 없습니다.',
    ja: 'カテゴリ商品が見つかりません。',
    zhCN: '分类商品找不到。',
    zhTW: '分類商品找不到。',
    en: 'Category product not found.',
  },
  'product.category.name.required': {
    ko: '기준 언어의 카테고리명은 필수 입력 값입니다.',
    ja: '基本言語のカテゴリ名は必須入力です。',
    zhCN: '基本语言的分类名称是必填输入值。',
    zhTW: '基本語言的分類名稱是必填輸入值。',
    en: 'The category name in the default language is required.',
  },
  'product.name.required': {
    ko: '기준 언어의 상품명은 필수 입력 값입니다.',
    ja: '基本言語の商品名は必須入力です。',
    zhCN: '基本语言的产品名称是必填输入值。',
    zhTW: '基本語言的商品名稱是必填輸入值。',
    en: 'The product name in the default language is required.',
  },
  'product.category.product.duplicate': {
    ko: '이미 연결된 상품입니다.',
    ja: 'すでに連携されている商品です。',
    zhCN: '该商品已关联。',
    zhTW: '該商品已關聯。',
    en: 'Product is already linked to this category.',
  },
  'product.name.duplicate': {
    ko: '상품 명이 중복되었습니다.',
    ja: '商品名が重複しました。',
    zhCN: '商品名称重复。',
    zhTW: '商品名稱重複。',
    en: 'Product name duplicate.',
  },
  'product.category.name.duplicate': {
    ko: '카테고리 명이 중복되었습니다.',
    ja: 'カテゴリ名が重複しました。',
    zhCN: '分类名称重复。',
    zhTW: '分類名稱重複。',
    en: 'Category name duplicate.',
  },
  'product.category.has_products': {
    ko: '연결된 상품이 있어 삭제할 수 없습니다.',
    ja: '連携されている商品があるため削除できません。',
    zhCN: '存在关联商品，无法删除。',
    zhTW: '存在關聯商品，無法刪除。',
    en: 'Cannot delete. Products are linked to this category.',
  },
  'product.category.translation.name.notChanged': {
    ko: '변경이 필요한 카테고리명이 수정되지 않았습니다.',
    ja: '変更が必要なカテゴリ名が修正されていません。',
    zhCN: '需要更改的分类名称未修改。',
    zhTW: '需要更改的分類名稱未修改。',
    en: 'Category name that needs to be changed has not been modified.',
  },
  'product.category.translation.imageId.notChanged': {
    ko: '변경이 필요한 카테고리 이미지 ID가 수정되지 않았습니다.',
    ja: '変更が必要なカテゴリ画像IDが修正されていません。',
    zhCN: '需要更改的分类图片ID未修改。',
    zhTW: '需要更改的分類圖片ID未修改。',
    en: 'Category image ID that needs to be changed has not been modified.',
  },
  'product.translation.name.notChanged': {
    ko: '변경이 필요한 상품명이 수정되지 않았습니다.',
    ja: '変更が必要な商品名が修正されていません。',
    zhCN: '需要更改的商品名称未修改。',
    zhTW: '需要更改的商品名稱未修改。',
    en: 'Product name that needs to be changed has not been modified.',
  },
  'product.translation.description.notChanged': {
    ko: '변경이 필요한 상품 설명이 수정되지 않았습니다.',
    ja: '変更が必要な商品説明が修正されていません。',
    zhCN: '需要更改的商品说明未修改。',
    zhTW: '需要更改的商品說明未修改。',
    en: 'Product description that needs to be changed has not been modified.',
  },
  'product.translation.imageId.notChanged': {
    ko: '변경이 필요한 상품 이미지 ID가 수정되지 않았습니다.',
    ja: '変更が必要な商品画像IDが修正されていません。',
    zhCN: '需要更改的商品图片ID未修改。',
    zhTW: '需要更改的商品圖片ID未修改。',
    en: 'Product image ID that needs to be changed has not been modified.',
  },
};
