export const PRODUCT_ERROR_MESSAGE = {
  'product.not_found': {
    ko: '상품을 찾을 수 없습니다.',
    ja: '商品を見つかりません。',
    zhCN: '商品找不到。',
    zhTW: '商品找不到。',
    en: 'Product not found.',
  },
  'product.event.not_found': {
    ko: '이벤트를 찾을 수 없습니다.',
    ja: 'イベントを見つかりません。',
    zhCN: '事件找不到。',
    zhTW: '事件找不到。',
    en: 'Event not found.',
  },
  'product.event.product.not_found': {
    ko: '이벤트 상품을 찾을 수 없습니다.',
    ja: 'イベント商品を見つかりません。',
    zhCN: '事件商品找不到。',
    zhTW: '事件商品找不到。',
    en: 'Event product not found.',
  },
  'product.event.name.required': {
    ko: '기준 언어의 이벤트명은 필수 입력 값입니다.',
    ja: '基本言語のイベント名は必須入力です。',
    zhCN: '基本语言的事件名称是必填输入值。',
    zhTW: '基本語言的事件名稱是必填輸入值。',
    en: 'The event name in the default language is required.',
  },
  'product.name.required': {
    ko: '기준 언어의 상품명은 필수 입력 값입니다.',
    ja: '基本言語の商品名は必須入力です。',
    zhCN: '基本语言的产品名称是必填输入值。',
    zhTW: '基本語言的商品名稱是必填輸入值。',
    en: 'The product name in the default language is required.',
  },
  'product.event.product.duplicate': {
    ko: '이미 연결된 상품입니다.',
    ja: 'すでに連携されている商品です。',
    zhCN: '该商品已关联。',
    zhTW: '該商品已關聯。',
    en: 'Product is already linked to this event.',
  },
  'product.menu_category.not_found': {
    ko: '메뉴 분류를 찾을 수 없습니다.',
    ja: 'メニューボード分類を見つかりません。',
    zhCN: '菜单分类找不到。',
    zhTW: '菜單分類找不到。',
    en: 'Menu category not found.',
  },
  'product.operation.not_found': {
    ko: '시술을 찾을 수 없습니다.',
    ja: 'オペレーションを見つかりません。',
    zhCN: '操作找不到。',
    zhTW: '操作找不到。',
    en: 'Operation not found.',
  },

  'product.category.name.required': {
    ko: '상품 분류 명은 필수 입력 값입니다.',
    ja: '商品分類名は必須入力です。',
    zhCN: '商品分类名称是必填输入值。',
    zhTW: '商品分類名稱是必填輸入值。',
    en: 'Product category name is required.',
  },
  'product.name.duplicate': {
    ko: '상품 명이 중복되었습니다.',
    ja: '商品名が重複しました。',
    zhCN: '商品名称重复。',
    zhTW: '商品名稱重複。',
    en: 'Product name duplicate.',
  },
  'product.category.name.duplicate': {
    ko: '상품 분류 명이 중복되었습니다.',
    ja: '商品分類名が重複しました。',
    zhCN: '商品分类名称重复。',
    zhTW: '商品分類名稱重複。',
    en: 'Product category name duplicate.',
  },
  'product.category.has_children': {
    ko: '하위 분류가 있습니다. 하위 분류를 삭제한 후 삭제해주세요.',
    ja: '下位分類があります。下位分類を削除した後、削除してください。',
    zhCN: '下级分类存在。请先删除下级分类后再删除。',
    zhTW: '下級分類存在。請先刪除下級分類後再刪除。',
    en: 'Sub-categories exist. Please delete sub-categories first, then delete.',
  },
  'product.category-main.not_found': {
    ko: '대분류를 찾을 수 없습니다.',
    ja: '大分類を見つかりません。',
    zhCN: '主分类找不到。',
    zhTW: '主分類找不到。',
    en: 'Main category not found.',
  },

  'product.event.name.duplicate': {
    ko: '이벤트 명이 중복되었습니다.',
    ja: 'イベント名が重複しました。',
    zhCN: '活动名称重复。',
    zhTW: '活動名稱重複。',
    en: 'Event name duplicate.',
  },
  'product.event.has_products': {
    ko: '연결된 상품이 있어 삭제할 수 없습니다.',
    ja: '連携されている商品があるため削除できません。',
    zhCN: '存在关联商品，无法删除。',
    zhTW: '存在關聯商品，無法刪除。',
    en: 'Cannot delete. Products are linked to this event.',
  },
  'product.event.translation.name.notChanged': {
    ko: '변경이 필요한 이벤트명이 수정되지 않았습니다.',
    ja: '変更が必要なイベント名が修正されていません。',
    zhCN: '需要更改的活动名称未修改。',
    zhTW: '需要更改的活動名稱未修改。',
    en: 'Event name that needs to be changed has not been modified.',
  },
  'product.event.translation.imageId.notChanged': {
    ko: '변경이 필요한 이벤트 이미지 ID가 수정되지 않았습니다.',
    ja: '変更が必要なイベント画像IDが修正されていません。',
    zhCN: '需要更改的活动图片ID未修改。',
    zhTW: '需要更改的活動圖片ID未修改。',
    en: 'Event image ID that needs to be changed has not been modified.',
  },

  'product.translation.name.notChanged': {
    ko: '변경이 필요한 상품명이 수정되지 않았습니다.',
    ja: '変更が必要な商品名が修正されていません。',
    zhCN: '需要更改的商品名称未修改。',
    zhTW: '需要更改的商品名稱未修改。',
    en: 'Product name that needs to be changed has not been modified.',
  },
  'product.translation.description.notChanged': {
    ko: '변경이 필요한 상품 설명이 수정되지 않았습니다.',
    ja: '変更が必要な商品説明が修正されていません。',
    zhCN: '需要更改的商品说明未修改。',
    zhTW: '需要更改的商品說明未修改。',
    en: 'Product description that needs to be changed has not been modified.',
  },
  'product.translation.imageId.notChanged': {
    ko: '변경이 필요한 상품 이미지 ID가 수정되지 않았습니다.',
    ja: '変更が必要な商品画像IDが修正されていません。',
    zhCN: '需要更改的商品图片ID未修改。',
    zhTW: '需要更改的商品圖片ID未修改。',
    en: 'Product image ID that needs to be changed has not been modified.',
  },
};